sudo: false

language: scala

scala:
  - 2.12.10
  - 2.13.0

jdk:
  - openjdk11

script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test

after_success: sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls

notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
      secure: "D2KLxUurS+0l6rXp6YWoOgkuSXl2Hx5m+kogAf1iEUicn4PnxTPSBT32EiR57RlYexfAyo9MyeJQFcjq073lXKEJQ1m04wXOlfoxlUVawxkcsN/tNL8YB22g0ysHSDav3TEszSwFhZbuc7BFl7BbhwpmKJr5S1qEGV9OD9DyTFg5JI7T9ngKvtutMLTrQtHbTsUd/1Dt+tGpCKN2yaUmv6QX/K69XUjy6ItE1+PiZhqggoIOphYrDbtQUxcgiQHi4FKZbn6J8Vf1AT/1Updyv/rCD3BO6HFACnnltFC2KgO6uvCFTVRwZLpZ1bB/EbjGI3c8IwrTSMK5+i0nrTL+tngrflb5TENWmH5FgOmH1/fl8KkQq3idEVfk7QMyafW1TJ1pxHSsZPmndVlubepjdo5O7duG9IyvYvQhU701Bcyn1RJkYj6IH+s8S3K5wlnVIdN00DUvkO+kd770qxlsBuiOd3pXHqJ9wNU+T4R7Lr6Y2/PIqrNJdNs9RVU5tCYKwr/zUh66fMFTJSrsVxV4r5AjdiVms+sRInsV+4byB70azpQvSonlTdvZnh811QQ6E08BsOqb1mUJYfpSqtiUxvSnhCG28rNkAzOx2F4uwpji01s6+BY8UMfRk4j+uaWsKTp/x8aieEpD672IOzyRaov86xDPOEtqYMv9H3a+KRw="

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete