name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala:
          - 2.13.4
          - 2.12.12

    services:
      pulsar:
        image: apachepulsar/pulsar-standalone:2.7.0
        ports:
          - 6650:6650
          - 8080:8080
        options: >-
          --health-cmd "curl -s http://pulsar:8080/admin/v2/namespaces/public"
          --health-interval 1s
          --health-timeout 5s
          --health-retries 100

    steps:
      - uses: actions/checkout@v2

      - uses: coursier/cache-action@v5

      - name: scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: openjdk@1.11

      - name: build ${{ matrix.scala }}
        run: sbt ++${{ matrix.scala }} clean coverage test
        env:
          PULSAR_HOST: localhost
          PULSAR_PORT: 6650

      - name: test coverage
        if: success()
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: sbt ++${{ matrix.scala }} coverageReport coverageAggregate coveralls

#      - name: slack
#        uses: homoluctus/slatify@master
#        if: failure() && github.ref == 'refs/heads/master'
#        with:
#          type: ${{ job.status }}
#          job_name: Build
#          url: ${{ secrets.SLACK_WEBHOOK }}